AWSTemplateFormatVersion: 2010-09-09
# Description: |
  
# Parameters: 
  
# Mappings: 
  
Resources:
  latifTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: "String"
      HealthCheckPort: "String"
      HealthCheckProtocol: "String"
      HealthCheckTimeoutSeconds: Number
      HealthyThresholdCount: Number
      IpAddressType: "String"
      Matcher:
        GrpcCode: "String"
        HttpCode: "String"
      Name: "String"
      Port: Number
      Protocol: "String"
      ProtocolVersion: "String"
      Tags:
        Tags
      TargetGroupAttributes:
        TargetGroupAttributes
      TargetType: "String"
      Targets:
        Targets
      UnhealthyThresholdCount: Number
      VpcId: "String"
  LatifSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH and HTTP # Required  
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: "String"  # add later
  
# Outputs: